<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { MarkdownRenderer } from 'x-markdown-vue'
import 'x-markdown-vue/style'
import { deleteManagedProblem, deleteOwnProblem, getManagedProblem, getOwnProblem, getProblemImage, listAuthoringCategories, listAuthoringSubjects, listManagedProblems, listOwnProblems, setManagedProblemStatus, setOwnProblemStatus, updateManagedProblem, updateOwnProblem } from '@/api/problemSolving'

const { ownOnly } = defineProps({ ownOnly: { type: Boolean, default: false } })
const problems = ref([]); const total = ref(0); const pagination = ref({ pageNum: 1, pageSize: 10 })
const detail = ref(null); const detailVisible = ref(false); const detailLoading = ref(false); const imageUrls = ref({})
const editVisible = ref(false); const editLoading = ref(false); const editSaving = ref(false); const editImages = ref([])
const editId = ref(null)
const subjects = ref([]); const categories = ref([])
const editForm = reactive({ subjectId: null, categoryId: null, title: '', intro: '', difficulty: '中等', tags: '', sceneType: 'textOnly', stem: '', standardAnswer: '', answerAnalysis: '' })
const editCategories = computed(() => categories.value.filter(item => !editForm.subjectId || item.subjectId === editForm.subjectId))
const editSubject = computed(() => subjects.value.find(item => item.id === editForm.subjectId))
const editSceneTemplates = computed(() => editSubject.value?.code === 'MATH' ? [
  { label: '纯文字', value: 'textOnly' }, { label: '平面 XY 坐标系', value: 'coordinatePlane2d' }, { label: '空间 XYZ 坐标系', value: 'coordinate3d' },
  { label: '平面几何', value: 'geometry2d' }, { label: '立体几何', value: 'geometry3d' }, { label: '统计图表', value: 'statistics2d' }, { label: '概率树状图', value: 'probabilityTree' },
] : editSubject.value?.code === 'PHYSICS' ? [
  { label: '弹簧测力计拉木块', value: 'mechanics2d' }, { label: '斜面机械效率', value: 'physicsInclinedPlane' }, { label: '水平碰撞', value: 'physicsCollision' },
  { label: '滑轮', value: 'physicsPulley' }, { label: '平面镜反射', value: 'physicsReflection' }, { label: '通电螺线管', value: 'physicsMagneticField' }, { label: '串联电路', value: 'physicsCircuit' }, { label: '纯文字', value: 'textOnly' },
] : [{ label: '纯文字', value: 'textOnly' }])
watch(() => editForm.subjectId, () => { if (!editCategories.value.some(item => item.id === editForm.categoryId)) editForm.categoryId = null })
async function loadData() { const data = await (ownOnly ? listOwnProblems(pagination.value) : listManagedProblems(pagination.value)); problems.value = data.records || []; total.value = Number(data.total) || 0 }
async function toggle(row) { try { await (ownOnly ? setOwnProblemStatus(row.id, row.status === 1 ? 0 : 1) : setManagedProblemStatus(row.id, row.status === 1 ? 0 : 1)); await loadData() } catch (error) { ElMessage.error(error.message || '更新失败') } }
async function remove(row) { try { await ElMessageBox.confirm(`确定删除题目“${row.title}”吗？关联题图和题目版本会一并删除，无法恢复。`, '删除题目', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' }); await (ownOnly ? deleteOwnProblem(row.id) : deleteManagedProblem(row.id)); ElMessage.success('题目已删除'); if (problems.value.length === 1 && pagination.value.pageNum > 1) pagination.value.pageNum -= 1; await loadData() } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error(error.message || '删除失败') } }
function clearImageUrls() { Object.values(imageUrls.value).forEach(url => URL.revokeObjectURL(url)); imageUrls.value = {} }
async function view(row) { detailVisible.value = true; detailLoading.value = true; detail.value = null; clearImageUrls(); try { detail.value = await (ownOnly ? getOwnProblem(row.id) : getManagedProblem(row.id)); const entries = await Promise.all((detail.value.images || []).map(async image => { try { const response = await getProblemImage(image.url); return [image.id, URL.createObjectURL(response.data)] } catch { return [image.id, ''] } })); imageUrls.value = Object.fromEntries(entries) } catch (error) { ElMessage.error(error.message || '加载题目详情失败') } finally { detailLoading.value = false } }
function closeDetail() { detail.value = null; clearImageUrls() }
function clearEditImages() { editImages.value.forEach(item => { if (item.url?.startsWith('blob:')) URL.revokeObjectURL(item.url) }); editImages.value = [] }
function sceneTypeOf(definition) { return definition?.sceneDefinition?.sceneType || 'textOnly' }
async function openEdit(row) {
  editId.value = row.id; editVisible.value = true; editLoading.value = true; clearEditImages()
  try {
    const item = await (ownOnly ? getOwnProblem(row.id) : getManagedProblem(row.id))
    Object.assign(editForm, { subjectId: item.subjectId, categoryId: item.categoryId, title: item.title || '', intro: item.intro || '', difficulty: item.difficulty || '中等', tags: (item.tags || []).join('，'), sceneType: sceneTypeOf(item.definition), stem: item.definition?.stem || '', standardAnswer: item.standardAnswer || '', answerAnalysis: item.answerAnalysis || '' })
  } catch (error) { editVisible.value = false; ElMessage.error(error.message || '加载题目详情失败') } finally { editLoading.value = false }
}
function editDefinition() {
  const common = { stem: editForm.stem.trim(), facts: { answer: editForm.standardAnswer.trim() }, evaluation: { acceptedAnswers: editForm.standardAnswer.split(/[，,]/).map(item => item.trim()).filter(Boolean), misconceptions: [] }, visualCatalog: [] }
  if (editForm.sceneType === 'coordinate2d') return { ...common, sceneDefinition: { sceneType: 'coordinate2d', variables: { t: { value: 1, min: 0, max: 3 } } }, visualCatalog: ['show-perpendicular-height', 'highlight-AB'] }
  if (editForm.sceneType === 'mechanics2d') return { ...common, sceneDefinition: { sceneType: 'mechanics2d', variables: {} }, visualCatalog: ['show-spring-force'] }
  if (editForm.sceneType.startsWith('physics')) return { ...common, sceneDefinition: { sceneType: editForm.sceneType, variables: {} } }
  if (editForm.sceneType !== 'textOnly') return { ...common, sceneDefinition: { sceneType: editForm.sceneType, variables: {}, entities: [] }, visualCatalog: ['draw-math-scene'] }
  return { ...common, sceneDefinition: { sceneType: 'textOnly', variables: {} } }
}
function handleEditImageChange(file) { if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.raw?.type) || file.raw.size > 10 * 1024 * 1024) { editImages.value = editImages.value.filter(item => item.uid !== file.uid); ElMessage.warning('仅支持 jpg、jpeg、png、webp 图片，且不能超过 10MB'); return } file.url = URL.createObjectURL(file.raw) }
function handleEditImageRemove(file) { if (file.url?.startsWith('blob:')) URL.revokeObjectURL(file.url) }
async function saveEdit() {
  if (!editForm.categoryId || !editForm.title.trim() || !editForm.intro.trim() || !editForm.stem.trim() || !editForm.standardAnswer.trim() || !editForm.answerAnalysis.trim()) { ElMessage.warning('请完成题目、分类、题干、标准答案和答案解析'); return }
  editSaving.value = true
  try {
    const data = new FormData(); data.append('request', new Blob([JSON.stringify({ categoryId: editForm.categoryId, title: editForm.title, intro: editForm.intro, difficulty: editForm.difficulty, tags: editForm.tags.split(/[，,]/).map(item => item.trim()).filter(Boolean), standardAnswer: editForm.standardAnswer.trim(), answerAnalysis: editForm.answerAnalysis.trim(), definition: editDefinition() })], { type: 'application/json' })); editImages.value.forEach(item => data.append('images', item.raw))
    await (ownOnly ? updateOwnProblem(editId.value, data) : updateManagedProblem(editId.value, data))
    ElMessage.success('题目已保存'); editVisible.value = false; await loadData()
  } catch (error) { ElMessage.error(error.message || '保存失败') } finally { editSaving.value = false }
}
async function loadBase() { try { subjects.value = await listAuthoringSubjects(); categories.value = await listAuthoringCategories() } catch (error) { ElMessage.error(error.message || '加载分类失败') } }
function changePage(pageNum) { pagination.value.pageNum = pageNum; loadData() }
function changeSize(pageSize) { pagination.value = { pageNum: 1, pageSize }; loadData() }
onMounted(() => { loadData().catch(error => ElMessage.error(error.message || '加载失败')); loadBase() })
</script>

<template>
  <main class="manage-page">
    <header><p>{{ ownOnly ? 'TEACHER · PROBLEM SOLVING' : 'ADMIN · PROBLEM SOLVING' }}</p><h1>题目管理</h1><span>{{ ownOnly ? '管理自己创建的讲题题目。' : '维护讲题题目的上下架状态和删除操作。' }}</span></header>
    <section class="table-panel"><el-table :data="problems" border><el-table-column prop="title" label="题目" min-width="220"/><el-table-column prop="subject" label="科目" width="110"/><el-table-column prop="category" label="分类" width="130"/><el-table-column prop="difficulty" label="难度" width="90"/><el-table-column v-if="!ownOnly" prop="creatorId" label="创建者 ID" width="110"><template #default="{ row }">{{ row.creatorId ?? '-' }}</template></el-table-column><el-table-column v-if="!ownOnly" prop="creatorNickname" label="创建者昵称" min-width="120"/><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 1 ? 'success' : 'info'">{{ row.status === 1 ? '上架' : '下架' }}</el-tag></template></el-table-column><el-table-column label="操作" width="255"><template #default="{ row }"><el-button link type="primary" @click="view(row)">查看</el-button><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-button link :type="row.status === 1 ? 'warning' : 'success'" @click="toggle(row)">{{ row.status === 1 ? '下架' : '上架' }}</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><div v-if="total" class="pagination-bar"><el-pagination v-model:current-page="pagination.pageNum" v-model:page-size="pagination.pageSize" :page-sizes="[10, 20, 50]" :total="total" layout="total, sizes, prev, pager, next, jumper" background @size-change="changeSize" @current-change="changePage"/></div></section>
    <el-dialog v-model="detailVisible" class="problem-detail-dialog" width="min(920px, calc(100vw - 32px))" destroy-on-close @closed="closeDetail"><template #header><div class="detail-title"><span>题目详情</span><strong>{{ detail?.title || '正在加载题目...' }}</strong></div></template><el-skeleton v-if="detailLoading" animated :rows="9"/><article v-else-if="detail" class="detail-content"><section class="detail-overview"><div class="detail-label">所属科目</div><strong>{{ detail.subject }}</strong><div class="detail-label">题型分类</div><strong>{{ detail.category }}</strong><div class="detail-label">难度</div><strong>{{ detail.difficulty }}</strong><div class="detail-label">创建者 ID</div><strong>{{ detail.creatorId ?? '-' }}</strong><div class="detail-label">创建者昵称</div><strong>{{ detail.creatorNickname || '-' }}</strong><div class="detail-label">题目简介</div><p>{{ detail.intro || '暂无简介' }}</p></section><section class="detail-block"><h3>题干</h3><div class="markdown-surface"><MarkdownRenderer class="detail-markdown" :markdown="detail.definition?.stem || ''" :enable-latex="true"/></div></section><section v-if="detail.images?.length" class="detail-block"><h3>题图</h3><div class="problem-images"><el-image v-for="(image, index) in detail.images" :key="image.id" :src="imageUrls[image.id]" :alt="image.originalFilename" :preview-src-list="detail.images.map(item => imageUrls[item.id]).filter(Boolean)" :initial-index="index" fit="contain"/></div></section><section class="detail-block answer-block"><h3>标准答案</h3><div class="markdown-surface"><MarkdownRenderer class="detail-markdown" :markdown="detail.standardAnswer || '暂无标准答案'" :enable-latex="true"/></div></section><section class="detail-block"><h3>答案解析</h3><div class="markdown-surface"><MarkdownRenderer class="detail-markdown" :markdown="detail.answerAnalysis || '暂无答案解析'" :enable-latex="true"/></div></section></article><template #footer><el-button plain @click="detailVisible = false">关闭</el-button></template></el-dialog>
    <el-dialog v-model="editVisible" title="编辑题目" width="min(920px, calc(100vw - 32px))" destroy-on-close @closed="clearEditImages">
      <el-skeleton v-if="editLoading" animated :rows="10" />
      <el-form v-else label-width="92px" class="edit-form"><el-row :gutter="16"><el-col :span="12"><el-form-item label="科目"><el-select v-model="editForm.subjectId" class="full"><el-option v-for="item in subjects.filter(item => item.status === 1)" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="题型分类"><el-select v-model="editForm.categoryId" class="full"><el-option v-for="item in editCategories" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item></el-col></el-row><el-row :gutter="16"><el-col :span="12"><el-form-item label="题目名称"><el-input v-model="editForm.title" /></el-form-item></el-col><el-col :span="12"><el-form-item label="难度"><el-select v-model="editForm.difficulty" class="full"><el-option label="基础" value="基础" /><el-option label="中等" value="中等" /><el-option label="困难" value="困难" /></el-select></el-form-item></el-col></el-row><el-form-item label="题目简介"><el-input v-model="editForm.intro" /></el-form-item><el-form-item label="场景模板"><el-select v-model="editForm.sceneType" class="full"><el-option v-for="item in editSceneTemplates" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item label="题干"><el-input v-model="editForm.stem" type="textarea" :rows="6" /></el-form-item><el-form-item label="题图"><el-upload v-model:file-list="editImages" action="#" list-type="picture-card" accept="image/jpeg,image/png,image/webp" :auto-upload="false" :on-change="handleEditImageChange" :on-remove="handleEditImageRemove"><span>+</span></el-upload><small class="edit-hint">重新选择题图会替换原有题图，不选择则保留原题图</small></el-form-item><el-form-item label="标准答案"><el-input v-model="editForm.standardAnswer" type="textarea" :rows="6" /></el-form-item><el-form-item label="答案解析"><el-input v-model="editForm.answerAnalysis" type="textarea" :rows="6" /></el-form-item><el-form-item label="标签"><el-input v-model="editForm.tags" placeholder="多个标签用逗号分隔" /></el-form-item></el-form>
      <template #footer><el-button :disabled="editSaving" @click="editVisible = false">取消</el-button><el-button type="primary" :loading="editSaving" :disabled="editLoading" @click="saveEdit">保存</el-button></template>
    </el-dialog>
  </main>
</template>

<style scoped>
.manage-page { padding: 28px; color: #25334d; }.manage-page header { margin-bottom: 20px; }.manage-page header p { margin: 0; color: #66758d; font-size: 12px; font-weight: 700; }.manage-page h1 { margin: 5px 0; font-size: 28px; }.manage-page header span { color: #64748b; }.table-panel { margin-top: 18px; padding: 20px; border: 1px solid #dce4ef; border-radius: 8px; background: #fff; }.pagination-bar { display:flex; justify-content:flex-end; margin-top:18px; }.full { width: 100%; }.edit-form { max-height: 65vh; overflow: auto; padding-right: 8px; }.edit-hint { display: block; margin-top: -8px; color: #718096; font-size: 12px; }.detail-title { display:grid; gap:5px; padding-right:24px; }.detail-title span,.detail-label { color:#718096; font-size:12px; font-weight:600; }.detail-title strong { color:#1f2a44; font-size:20px; line-height:1.35; overflow-wrap:anywhere; }.detail-content { display:grid; gap:18px; max-height:64vh; overflow:auto; padding:2px 8px 2px 0; color:#25334d; }.detail-overview { display:grid; grid-template-columns:92px minmax(0,1fr) 92px minmax(0,1fr); gap:10px 14px; align-items:center; padding:16px; border:1px solid #dfe7f2; border-radius:8px; background:#f8fbff; }.detail-overview strong,.detail-overview p { margin:0; min-width:0; overflow-wrap:anywhere; }.detail-overview p { grid-column:span 3; color:#465572; line-height:1.6; }.detail-block { display:grid; gap:9px; }.detail-block h3 { margin:0; color:#25334d; font-size:16px; }.markdown-surface { min-width:0; padding:14px 16px; border:1px solid #e2e8f0; border-radius:6px; background:#ffffff; line-height:1.8; }.answer-block .markdown-surface { border-color:#cfe3d9; background:#f7fcf8; }.detail-markdown :deep(p:first-child),.detail-markdown :deep(h1:first-child),.detail-markdown :deep(h2:first-child),.detail-markdown :deep(h3:first-child) { margin-top:0; }.detail-markdown :deep(p:last-child) { margin-bottom:0; }.detail-markdown :deep(pre) { max-width:100%; overflow:auto; }.problem-images { display:flex; flex-wrap:wrap; gap:12px; }.problem-images :deep(.el-image) { width:min(100%, 300px); height:200px; border:1px solid #dce3ee; border-radius:6px; background:#f8fafc; }@media(max-width:760px){.manage-page{padding:18px}.table-panel{padding:14px;overflow-x:auto}.pagination-bar{justify-content:center}.detail-overview{grid-template-columns:82px minmax(0,1fr)}.detail-overview p{grid-column:span 1}.detail-overview .detail-label:nth-of-type(4){align-self:start}.markdown-surface{padding:12px}}
</style>
